---
# File: asserts.yml - Asserts for this playbook

- name: ping hosts
  ping:

- name: ensure all hosts are reachable
  run_once: yes
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: os_supported_matrix | check distribution
  assert:
    quiet: yes
    fail_msg: "{{ ansible_distribution }} is not supported for this role"
    that:
      - ansible_distribution in os_supported_matrix

- name: get os version to compare with
  set_fact:
    version_to_compare: "{{ item.value.min_version }}"
  loop: "{{ lookup('dict', os_supported_matrix) }}"
  no_log: yes
  when:
    - ansible_distribution in item.key

- name: os_supported_matrix | check distribution version
  assert:
    quiet: yes
    fail_msg: "{{ ansible_distribution_version }} is not supported for this role"
    that:
      - ansible_distribution_version is version('{{ version_to_compare }}', '>')
  when:
    - version_to_compare is defined
    - version_to_compare | length > 0

- name: Check nomad_group_name is included in groups
  fail:
    msg: "nomad_group_name must be included in groups."
  when: nomad_group_name not in groups
