---
# File: tasks/CentOS.yml - CentOS tasks for nomad

# Supposedly SELinux disrupts LXC (shrug)

- name: Stop SELinux enforcing
  shell: "setenforce 0"
  when: nomad_docker_enable == "true"

- name: Disable SELinux
  replace: dest=/etc/selinux/config regexp='^SELINUX=enforcing' replace='SELINUX=disabled'
  when: nomad_docker_enable == "true"

- name: OS Packages
  yum: "name={{ item }} state=present"
  with_items: "{{ nomad_centos_os_packages }}"
  tags: installation

- name: Download Nomad
  become: no
  connection: local
  get_url: "url={{ nomad_zip_url }} dest={{ role_path }}/files/{{ nomad_centos_pkg }} sha256sum={{ nomad_zip_sha256 }} timeout=74"
  run_once: true
  tags: installation

- name: Unarchive Nomad
  become: no
  connection: local
  unarchive: "src={{ role_path }}/files/{{ nomad_centos_pkg }} dest={{ role_path }}/files/ creates={{ role_path }}/files/consul"
  run_once: true
  tags: installation

- name: Install Nomad
  copy: "src={{ role_path }}/files/nomad dest=/usr/local/bin/ owner={{ nomad_user }} group={{ nomad_group }} mode=0755"
  tags: installation

- name: Cleanup
  become: no
  connection: local
  file: "dest={{ role_path }}/files/nomad* state=absent"
  run_once: true
  tags: installation
