---
# File: tasks/Debian.yml - Debian tasks for nomad

- name: OS Packages
  apt: "name={{ item }} state=present update_cache=yes"
  with_items: "{{ nomad_debian_os_packages }}"
  tags: installation

- name: Download Nomad
  become: no
  connection: local
  get_url: "url={{ nomad_zip_url }} dest={{ role_path }}/files/{{ nomad_debian_pkg }} sha256sum={{ nomad_zip_sha256 }} timeout=74"
  run_once: true
  tags: installation

- name: Unarchive Nomad
  become: no
  connection: local
  unarchive: "src={{ role_path }}/files/{{ nomad_debian_pkg }} dest={{ role_path }}/files/ creates={{ role_path }}/files/consul"
  run_once: true
  tags: installation

- name: Install Nomad
  copy: "src={{ role_path }}/files/nomad dest=/usr/local/bin/ owner={{ nomad_user }} group={{ nomad_group }} mode=0755"
  tags: installation

- name: Cleanup
  become: no
  connection: local
  file: "dest={{ role_path }}/files/nomad* state=absent"
  run_once: true
  tags: installation

## Docker Subsystem

- name: Update package cache
  apt: update_cache=yes
  when: nomad_enable_docker == "true"
  tags: docker

- name: Apt transport package
  apt: name='apt-transport-https' state=present
  when: nomad_enable_docker == "true"
  tags: docker

- name: CA certs package
  apt: name='ca-certificates' state=present
  when: nomad_enable_docker == "true"
  tags: docker

- name: Signing key
  apt_key: keyserver='p80.pool.sks-keyservers.net' id=58118E89F3A912897C070ADBF76221572C52609D
  when: nomad_enable_docker == "true"
  tags: docker

- name: Add Docker repo
  apt_repository: "repo={{ nomad_docker_debian_repo }} state=present"
  when: nomad_enable_docker == "true"
  tags: docker

- name: Install Docker
  apt: name='docker-engine' state=present update_cache=yes
  when: nomad_enable_docker == "true"
  tags: docker 

- name: Start Docker
  service: name=docker enabled=yes state=started
  when: nomad_enable_docker == "true"
  tags: docker

  
