---
# File: docker.yml - Docker tasks for nomad

## Docker items

# Fix for https://github.com/docker/docker/issues/23347
- name: Install dmsetup for Ubuntu 16.04
  apt:
    pkg: dmsetup
    state: "{{ dmsetup_pkg_state }}"
    update_cache: yes
    cache_valid_time: 600
  register: dmsetup_result
  when: ansible_distribution_version|version_compare(16.04, '=') and nomad_docker_enable == "true"
  tags: docker

- name: Run dmsetup for Ubuntu 16.04
  command: dmsetup mknodes
  when: dmsetup_result
  tags: docker
