---
- name: Create volume {{ item['name'] }}
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    owner: "{{ item['owner'] | default(nomad_user) }}"
    group: "{{ item['group'] | default(nomad_group) }}"
    state: directory
    mode: "{{ item['mode'] | default('0755') }}"
  with_items: "{{ nomad_host_volumes }}"
