---
# File: tasks/Ubuntu.yml - Ubuntu tasks for nomad

- name: OS Packages
  apt: "name={{ item }} state=present update_cache=yes"
  with_items: "{{ nomad_ubuntu_os_packages }}"
  tags: installation

- name: Download Nomad
  become: no
  connection: local
  get_url: "url={{ nomad_zip_url }} dest={{ role_path }}/files/{{ nomad_ubuntu_pkg }} sha256sum={{ nomad_zip_sha256 }} timeout=74"
  run_once: true
  tags: installation

- name: Unarchive Nomad
  become: no
  connection: local
  unarchive: "src={{ role_path }}/files/{{ nomad_ubuntu_pkg }} dest={{ role_path }}/files/ creates={{ role_path }}/files/consul"
  run_once: true
  tags: installation

- name: Install Nomad
  copy: "src={{ role_path }}/files/nomad dest=/usr/local/bin/ owner={{ nomad_user }} group={{ nomad_group }} mode=0755"
  tags: installation

- name: Cleanup
  become: no
  connection: local
  file: "dest={{ role_path }}/files/nomad* state=absent"
  run_once: true
  tags: installation

## Docker items

# Fix for https://github.com/docker/docker/issues/23347
- name: Install dmsetup for Ubuntu 16.04
  apt:
    pkg: dmsetup
    state: "{{ dmsetup_pkg_state }}"
    update_cache: yes
    cache_valid_time: 600
  register: dmsetup_result
  when: ansible_distribution_version|version_compare(16.04, '=') and nomad_docker_enable == "true"
  tags: docker

- name: Run dmsetup for Ubuntu 16.04
  command: dmsetup mknodes
  when: dmsetup_result and 
  tags: docker 
